# Dockerfile pour Traefik sur Raspberry Pi
FROM docker.io/library/traefik:v3.2

# Labels
LABEL maintainer="Audit IO"
LABEL description="Traefik reverse proxy pour le hall d'entrée"

# Exposition des ports
EXPOSE 80 443
